export const GENERATOR_CONFIG = {
  MIN_PRICE: 100,
  MAX_PRICE: 100000,
  MIN_RATING: 1,
  MAX_RATING: 5,
  MIN_ADULT_COUNT: 1,
  MAX_ADULT_COUNT: 10,
  MIN_REVIEW_COUNT: 0,
  MAX_REVIEW_COUNT: 3,
  FIRST_WEEK_DAY: 1,
  LAST_WEEK_DAY: 7,
} as const;
