export const GENERATOR_CONFIG = {
  MIN_PRICE: 50,
  MAX_PRICE: 2000,
  MIN_RATING: 1,
  MAX_RATING: 5,
  MIN_ADULT_COUNT: 1,
  MAX_ADULT_COUNT: 5,
  MIN_REVIEW_COUNT: 0,
  MAX_REVIEW_COUNT: 4,
  FIRST_WEEK_DAY: 1,
  LAST_WEEK_DAY: 7,
} as const;
