export const OFFER_FIELD_RESTRICTION = {
  TITLE_MIN_LENGTH: 10,
  TITLE_MAX_LENGTH: 100,
  DESCRIPTION_MIN_LENGTH: 20,
  DESCRIPTION_MAX_LENGTH: 1024,
  BEDROOMS_MIN: 1,
  BEDROOMS_MAX: 8,
  MAX_ADULTS_MIN: 1,
  MAX_ADULTS_MAX: 10,
  PRICE_MIN: 100,
  PRICE_MAX: 100_000,
} as const;
