# Получить объявление по идентификатору
GET http://localhost:4000/offers/65cd2547bb5a9353b77b8cab HTTP/1.1

###

## Получить список объявлений
GET http://localhost:4000/offers HTTP/1.1

###

GET http://localhost:4000/offers?limit=2 HTTP/1.1

###

## Создать новое объявление

POST http://localhost:4000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZGE1ODNjMzMxNWU0MGY4NzMxZThjYyIsImVtYWlsIjoidGVzdEB0ZXN0LmlvIiwibmFtZSI6IlN2ZXRhIEl2YW5vdmEiLCJhdmF0YXJVcmwiOiJhdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlhdCI6MTcwODgxMTMwNywiZXhwIjoxNzA4OTg0MTA3fQ.RD9oyQFmb4iGxy_UFko6yAVi8RGs4HxDnr79DXYYITA
Content-Type: application/json

{
  "title": "House in countryside",
  "date": "2024-02-19T14:00:31.727+00:00",
  "description": "Design interior in most sympathetic area!",
  "city": "Hamburg",
  "previewImage": "https://14.design.htmlacademy.pro/static/hotel/7.jpg",
  "images": [
    "https://14.design.htmlacademy.pro/static/hotel/12.jpg",
    "https://14.design.htmlacademy.pro/static/hotel/13.jpg",
    "https://14.design.htmlacademy.pro/static/hotel/14.jpg",
    "https://14.design.htmlacademy.pro/static/hotel/15.jpg",
    "https://14.design.htmlacademy.pro/static/hotel/16.jpg",
    "https://14.design.htmlacademy.pro/static/hotel/17.jpg"
  ],
  "premium": true,
  "favorite": true,
  "rating": 2,
  "type": "Room",
  "bedrooms": 1,
  "maxAdults": 4,
  "price": 55770,
  "goods": [
    "Baby seat",
    "Washer",
    "Towels",
    "Fridge"
  ],
  "userId": "65cd2547bb5a9353b77b8c95",
  "commentCount": 0,
  "location": {
    "latitude": 53.550341,
    "longitude": 10.000654
  }
}

###

## Удалить объявление по идентификатору

DELETE http://localhost:4000/offers/65da648ad20977c59206fbc1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZGE1ODNjMzMxNWU0MGY4NzMxZThjYyIsImVtYWlsIjoidGVzdEB0ZXN0LmlvIiwibmFtZSI6IlN2ZXRhIEl2YW5vdmEiLCJhdmF0YXJVcmwiOiJhdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlhdCI6MTcwODgxMTMwNywiZXhwIjoxNzA4OTg0MTA3fQ.RD9oyQFmb4iGxy_UFko6yAVi8RGs4HxDnr79DXYYITA

###

## Обновить объявление

PATCH http://localhost:4000/offers/65da65c1d20977c59206fbd2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZGE1ODNjMzMxNWU0MGY4NzMxZThjYyIsImVtYWlsIjoidGVzdEB0ZXN0LmlvIiwibmFtZSI6IlN2ZXRhIEl2YW5vdmEiLCJhdmF0YXJVcmwiOiJhdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlhdCI6MTcwODgxMTMwNywiZXhwIjoxNzA4OTg0MTA3fQ.RD9oyQFmb4iGxy_UFko6yAVi8RGs4HxDnr79DXYYITA
Content-Type: application/json

{
  "title": "Test title",
  "price": 777,
  "goods": []
}

###

## Список комментариев к объявлению
GET http://localhost:4000/offers/65da65c1d20977c59206fbd2/comments HTTP/1.1

###

## Список премиальные предложений для города (возвращает не больше 3 предложений). Доступен авторизованным и анонимным клиентам

 GET http://localhost:4000/offers/Brussels/premium HTTP/1.1

###

## Получить избранные предложения пользователя

GET http://localhost:4000/offers/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY1ZGE1ODNjMzMxNWU0MGY4NzMxZThjYyIsImVtYWlsIjoidGVzdEB0ZXN0LmlvIiwibmFtZSI6IlN2ZXRhIEl2YW5vdmEiLCJhdmF0YXJVcmwiOiJkZWZhdWx0LWF2YXRhci5wbmciLCJ0eXBlIjoicHJvIiwiaWF0IjoxNzA5MzAwNzI3LCJleHAiOjE3MDk0NzM1Mjd9.cpIMNHQD3B3jbQ1-XQcgOGylgTRMdx-HR5q3b4NrmmU
